version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: blog-app
    networks:
        - springboot-mysql-net

  springboot-blog-application-rest-api:
    container_name: springboot-blog-application-rest-api
    image: nguyenphucphat/springboot-blog-application-rest-api
    ports:
        - "8080:8080"
    depends_on:
        - mysqldb
    networks:
        - springboot-mysql-net
    restart: on-failure

networks:
  springboot-mysql-net:
    driver: bridge